export enum ErrorCode {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',

    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',

    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    EXPIRED_ACCESS_TOKEN = 'EXPIRED_ACCESS_TOKEN',
    EXPIRED_REFRESH_TOKEN = 'EXPIRED_REFRESH_TOKEN',
}
